[intake]
rollerSpeed = 0.70
extendTargetSpeed = 0.7
intakeRetractedPosition = 0.0
intakeExtendedPosition = 1.0

[shooter]
speed.near = 2450 # RPM
speed.auto = 2200 # RPM
speed.far = 2750
speed.reverse = -1000
speed.lowHub = 1000
motor.p = 0.0007
motor.i = 0.0
motor.d = 0.0
motor.ff = 0.00020
motor.minValue = -1.0
motor.maxValue = 1.0
motor.izone = 1.0

[climber]
servo1.unlockPosition = 0.0
servo1.lockPosition = 0.2

servo2.unlockPosition = 0.65
servo2.lockPosition = 1.0

innerRotationZeroOffset = 0.962
outerRotationZeroOffset = 0.023

extendSpeed = 0.25
retractSpeed = -0.25

inchesPerRevolution = 0.128325 # equal to 2.5665 / 20, meaning 2.5665 inches per 20 revolutions

innerStaticFriction = 0.20 # actual value unknown
outerStaticFriction = 0.20 # actual value unknown
innerStaticFrictionWithLoad = 0.35 # actual value unknown
outerStaticFrictionWithLoad = 0.35 # actual value unknown

[command.climb.midbar]
initialExtension = 16.0
liftRetraction = 1.0
verticalArmAngle = 0.0

[cycleCommand]
    inner.liftOffExtension = 20.0
    inner.backOffAngle = -4.0
    inner.nextBarAngle = 5.5
    inner.nextBarExtension = 28.0
    inner.dropToNextBarAngle = 16.0
    inner.grabNextBarExtension = 0.0
    inner.verticalArmAngle = 2.0
    inner.liftExtension = 18.0
    inner.toPreviousBarExtension = 20.0       # test value: needs calibration
    inner.zeroExtension = 3.0
    inner.releasePreviousBarExtension = 27.0
    inner.dropOffPreviousBarAngle = -15.7

    outer.liftOffExtension = 20.0
    outer.backOffAngle = -2.0
    outer.nextBarAngle = 8.50
    outer.nextBarExtension = 28.0
    outer.dropToNextBarAngle = 16.0
    outer.grabNextBarExtension = 0.0
    outer.verticalArmAngle = 7.0
    outer.liftExtension = 18.0
    outer.toPreviousBarExtension = 19.0       # test value: needs calibration
    outer.zeroExtension = 3.0
    outer.releasePreviousBarExtension = 24.0
    outer.dropOffPreviousBarAngle = -13.0

[drivetrain]
    [drivetrain.PID]
    k_maxOutput = 1.0
    k_minOutput = -1.0
        [drivetrain.PID.Drive]
            [drivetrain.PID.Drive.Motor1]
                k_P = 0.0
                k_I = 0.0
                k_D = 0.0
                k_FF = 0.0
                k_IZone = 0.0
            [drivetrain.PID.Drive.Motor2]
                k_P = 0.0
                k_I = 0.0
                k_D = 0.0
                k_FF = 0.0
                k_IZone = 0.0
            [drivetrain.PID.Drive.Motor3]
                k_P = 6e-5
                k_I = 1e-6
                k_D = 0.0
                k_FF = 0.000015
                k_IZone = 0.0
            [drivetrain.PID.Drive.Motor4]
                k_P = 6e-5
                k_I = 1e-6
                k_D = 0.0
                k_FF = 0.000015
                k_IZone = 0.0
        [drivetrain.PID.Steer]
            [drivetrain.PID.Steer.Motor1]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
            [drivetrain.PID.Steer.Motor2]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
            [drivetrain.PID.Steer.Motor3]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
            [drivetrain.PID.Steer.Motor4]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
    [drivetrain.EncoderSetpoint]
        Steer1GlobalOffset = 342.773
        Steer2GlobalOffset = 276.064
        Steer3GlobalOffset = 297.422
        Steer4GlobalOffset = 95.537
