[intake]
rollerSpeed = 1.0
extendTargetSpeed = 0.7
intakeRetractedPosition = 0.0
intakeExtendedPosition = 90.0

[shooter]
speed.near = 0.1
speed.far = 0.5
motor.p = 0.001
motor.i = 0.0
motor.d = 0.0
motor.ff = 0.0
motor.minValue = -1.0
motor.maxValue = 1.0
motor.izone = 1.0

[climber]
lockServoPosition = 0.0 # actual value unknown
extendSpeed = 1.0
retractSpeed = 1.0
inchesPerRevolution = 0.128325 # equal to 2.5665 / 20, meaning 2.5665 inches per 20 revolutions
innerStaticFriction = 0.0 # actual value unknown
outerStaticFriction = 0.0 # actual value unknown
innerStaticFrictionWithLoad = 0.0 # actual value unknown
outerStaticFrictionWithLoad = 0.0 # actual value unknown

[cycleCommand]
initalExtension = 0.0
liftExtension = 2.42
armAngleForNextBar = 0.0
extendToNextBarExtension = 0.0
dropToNextBar = 0.0
grabNextBarExtension = 0.0
releaseRearBar = 0.0
dropOffRearBar = 0.0
extendToRearBar = 0.0
armAngleVertical = 0.5
restingExtension = 0.0

[drivetrain]
    [drivetrain.PID]
    k_maxOutput = 1.0
    k_minOutput = -1.0
        [drivetrain.PID.Drive]
            [drivetrain.PID.Drive.Motor1]
                k_P = 0.0
                k_I = 0.0
                k_D = 0.0
                k_FF = 0.0
                k_IZone = 0.0
            [drivetrain.PID.Drive.Motor2]
                k_P = 0.0
                k_I = 0.0
                k_D = 0.0
                k_FF = 0.0
                k_IZone = 0.0
            [drivetrain.PID.Drive.Motor3]
                k_P = 6e-5
                k_I = 1e-6
                k_D = 0.0
                k_FF = 0.000015
                k_IZone = 0.0
            [drivetrain.PID.Drive.Motor4]
                k_P = 6e-5
                k_I = 1e-6
                k_D = 0.0
                k_FF = 0.000015
                k_IZone = 0.0
        [drivetrain.PID.Steer]
            [drivetrain.PID.Steer.Motor1]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
            [drivetrain.PID.Steer.Motor2]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
            [drivetrain.PID.Steer.Motor3]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
            [drivetrain.PID.Steer.Motor4]
                k_P = 0.0575
                k_I = 0.0125
                k_D = 0.005
                k_FF = 0.001
                k_IZone = 0.05
    [drivetrain.EncoderSetpoint]
        Steer1GlobalOffset =   18.99
        Steer2GlobalOffset =  -89.82
        Steer3GlobalOffset =   64.33
        Steer4GlobalOffset =  -95.45