[intake]
rollerSpeed = 1.0
extendTargetSpeed = 0.7
retractTargetSpeed = 0.7
deploySpeedFactor = 0.01
intakeRetractedPosition = 0.0
intakeExtendedPosition = 90.0


[shooter]
speed.near = 0.1
speed.far = 0.5
motor.p = 0.001
motor.i = 0.0
motor.d = 0.0
motor.ff = 0.0
motor.minValue = -1.0
motor.maxValue = 1.0
motor.izone = 1.0