[intake]
rollerSpeed = 1.0
extendTargetSpeed = 0.7
retractTargetSpeed = 0.7
deploySpeedFactor = 0.01
intakeRetractedPosition = 0.0
intakeExtendedPosition = 90.0

[climber]
lockServoPosition
extendSpeed
retractSpeed
innerStaticFriction
outerStaticFriction
innerStaticFrictionWithLoad
outerStaticFrictionWithLoad